services:
  telegram_bot_db:
    image: postgis/postgis:13-3.4
    container_name: telegram_bot_db
    volumes:
      - telegram_bot_db:/var/lib/postgresql/data
    restart: always
    network_mode: host
    env_file: .env

#  telegram_bot:
#    build: .
#    network_mode: host
#    dns:
#      - 185.51.200.2
#      - 178.22.122.100
#    env_file: .env
#    depends_on:
#      - telegram_bot_db

volumes:
  telegram_bot_db:
    driver: local
